INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f1bc3a27-a3b7-4401-91a8-6a844f84daf0',
  '20th-avenue-memory',
  '20th Avenue Memory',
  'DAH-TAM-028',
  'Soft blush-pink with a creamy center.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/20th-avenue-memory.jpg',
  'varieties/legacy/20th-avenue-memory.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b7c5b58e-0f74-4cbe-acac-a5d1f769ead0',
  'a-la-mode',
  'A La Mode',
  'DAH-ALM-029',
  'Striking orange with distinct white tips.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/a-la-mode.jpg',
  'varieties/legacy/a-la-mode.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '03929182-9457-40fe-8784-4045e0d1bff6',
  'american-dawn',
  'American Dawn',
  'DAH-AMD-030',
  'Deep coral-orange with purple/magenta center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/american-dawn.jpg',
  'varieties/legacy/american-dawn.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4d7996a2-b8c5-431e-8e77-21f27dee3fdc',
  'apple-blossom',
  'Apple Blossom',
  'DAH-APB-001',
  'Creamy yellow with soft blush pink edges.',
  1200,
  NULL,
  'sold-out',
  'collarette',
  '["pink","blush"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/apple-blossom.jpg',
  'varieties/legacy/apple-blossom.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f933bc3c-46af-4d9b-9ac4-68d5c90f7f74',
  'blizzard',
  'Blizzard',
  'DAH-NEW-101',
  'Pure white with a delicate dusting of ivory.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/blizzard.jpg',
  'varieties/legacy/blizzard.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2dfdf01e-0da4-4467-b97a-fb9ada8d5f5d',
  'bloomquist-alan',
  'Bloomquist Alan',
  'DAH-BQA-002',
  'Peachy-pink blend.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bq-alan.jpg',
  'varieties/legacy/bq-alan.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1e0ac4cf-2854-404f-a84b-bf07cfec54c4',
  'bloomquist-jean',
  'Bloomquist Jean',
  'DAH-BJN-032',
  'Vivid coppery-orange fading to sunset tones.',
  2200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bq-jean.jpg',
  'varieties/legacy/bq-jean.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f1088462-3db2-4db6-aa8b-9dd93054dd80',
  'bloomquist-mojo',
  'Bloomquist Mojo',
  'DAH-BQM-003',
  'Deep vibrant pink with hints of yellow/orange.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5 inches',
  '5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bq-mojo.jpg',
  'varieties/legacy/bq-mojo.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd384006f-1e53-4240-be57-f507beef0f0b',
  'bloomquist-tory-p',
  'Bloomquist Tory P',
  'DAH-BTP-033',
  'Soft blush with lavender-pink centers.',
  2500,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bq-tory-p.jpg',
  'varieties/legacy/bq-tory-p.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '08f0c79c-8ee1-4acb-9ef4-7816b9ba8906',
  'bocherell',
  'Bocherell',
  'DAH-BOC-114',
  'A workhorse in the garden. Pumps out flowers until frost. Soft butter yellow with a hint of blush.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["yellow"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bocherell.jpg',
  'varieties/legacy/bocherell.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '19f1288e-83d9-4fcb-aced-2981b2f7a400',
  'boom-boom-white',
  'Boom Boom White',
  'DAH-BBW-031',
  'Large white with a creamy center.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/boom-boom-white.jpg',
  'varieties/legacy/boom-boom-white.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b724fcd5-a91f-489c-b24a-bb174d86400d',
  'bracken-palomino',
  'Bracken Palomino',
  'DAH-NEW-102',
  'Bronze base with soft peachy accents.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'dde85889-307a-411f-a687-d73ade2555c3',
  'bracken-rose',
  'Bracken Rose',
  'DAH-BKR-004',
  'Exquisite dusty rose ("ballet slipper pink").',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bracken-rose.jpg',
  'varieties/legacy/bracken-rose.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b2a603bc-2efb-41eb-b270-b614cd894c30',
  'bracken-sarah',
  'Bracken Sarah',
  'DAH-NEW-103',
  'Creamy golden yellow with peach highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c94137ff-5c7d-4a4e-b053-0f59ec3dac58',
  'bride-to-be',
  'Bride to Be',
  'DAH-NEW-104',
  'Pure white with a hint of pale yellow at the center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/bride-to-be.jpg',
  'varieties/legacy/bride-to-be.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ecf4072d-f2ba-4ae0-b921-3e20267a8a91',
  'brown-sugar',
  'Brown Sugar',
  'DAH-NEW-105',
  'Rusty orange with reddish center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/brown-sugar.jpg',
  'varieties/legacy/brown-sugar.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'dcb259ef-be87-4c38-b5fd-89ec84d2a52f',
  'budapest-blush',
  'Budapest Blush',
  'DAH-NEW-106',
  'Soft pink, occasionally with white.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '57808a1e-3c65-4a30-868d-8ab122e33280',
  'cafe-au-lait',
  'Cafe Au Lait',
  'DAH-NEW-107',
  'Famous cream/blush/beige shift; very variable.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9f12a53f-a0ab-4e4a-a749-4b2a24d45e1f',
  'caitlynns-joy',
  'Caitlynns Joy',
  'DAH-NEW-108',
  'Hot pink/purple with apricot highlights.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '24eb330f-4492-4548-a0dd-7d0320a012c0',
  'cal-mini',
  'Café au Lait Mini',
  'DAH-CLM-005',
  'Creamy blush/pink (smaller Cafe Au Lait type).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '3-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/CAL-mini.jpg',
  'varieties/legacy/CAL-mini.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c3e9e0fc-f41e-4340-9540-5e512089a80a',
  'castle-drive',
  'Castle Drive',
  'DAH-CSD-007',
  'Soft blush-pink with yellow highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/castle-drive.jpg',
  'varieties/legacy/castle-drive.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'bb904118-40a7-4b93-8088-0efd50742e94',
  'chewy',
  'Chewy',
  'DAH-CHW-034',
  'Peachy buff with a lavender dusting (bronzed look).',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/chewy.jpg',
  'varieties/legacy/chewy.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3047bfdc-766b-4c51-bc78-a15c70e36173',
  'clearview-peachy',
  'Clearview Peachy',
  'DAH-CLP-035',
  'Muted peachy-pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/clearview-peachy.jpg',
  'varieties/legacy/clearview-peachy.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd397a68e-44f6-4fd4-b5d0-84de48836e59',
  'colorado-classic',
  'Colorado Classic',
  'DAH-NEW-109',
  'Ivory petals edged with vivid candy-pink.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '927f86f7-0cbd-44e3-bd13-e89a76d2a172',
  'copper-boy',
  'Copper Boy',
  'DAH-NEW-110',
  'Glowing copper, bronze, and burnt orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ba97c9bc-95a5-477b-b93c-702a30876604',
  'coralie',
  'Coralie',
  'DAH-COR-008',
  'Soft blush pink with subtle lavender tones.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/coralie.jpg',
  'varieties/legacy/coralie.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd806e953-3b1c-4f59-b870-4b717f3b5602',
  'cornel-bronze',
  'Cornel Bronze',
  'DAH-NEW-112',
  'Rich bronze and copper.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a47fb0b3-5c85-47e6-91b5-99eb23d9524d',
  'cornel',
  'Cornel',
  'DAH-NEW-111',
  'Dark cherry-red ball.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/cornel.png',
  'varieties/legacy/cornel.png',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '54e76d4b-8c0e-48ab-b28e-6ea3237c7dd0',
  'coseytown-bounty',
  'Coseytown Bounty',
  'DAH-NEW-113',
  'Peachy-orange with golden hues.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2cae54c0-ead6-4a34-aee6-5cca81803104',
  'creamy',
  'Creamy',
  'DAH-CRM-026',
  'Soft butter yellow.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/creamy.jpg',
  'varieties/legacy/creamy.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2106a2a6-568f-4578-bada-8fb63ab5af4a',
  'creme-de-cassis',
  'Crème De Cassis',
  'DAH-CDK-036',
  'Lavender/mauve top with dark berry/wine reverse.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/creme-de-cassis.jpg',
  'varieties/legacy/creme-de-cassis.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'cff891f3-7b7a-40a4-8f50-b61e55cb44e0',
  'crighton-honey',
  'Crichton Honey',
  'DAH-CRH-037',
  'Blend of creamy lemon, soft peach, and apricot.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/crighton-honey.jpg',
  'varieties/legacy/crighton-honey.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6e0afd8f-0256-4118-b2a9-189111f084da',
  'diva',
  'Diva',
  'DAH-DIV-114',
  'Deep velvety purple to dark raspberrry.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/diva.jpg',
  'varieties/legacy/diva.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9224c84d-06de-47fd-b634-dc14c284d4e7',
  'eveline',
  'Eveline',
  'DAH-NEW-114',
  'White with faint lavender tips/center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8b6f0fd7-50ef-479a-a19c-9b188d0665b1',
  'ferncliff-copper',
  'Ferncliff Copper',
  'DAH-NEW-115',
  'Soft copper-orange with yellow accents.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6a4084ff-f47d-44fa-8112-46d791cf6f5f',
  'ferncliff-rusty',
  'Ferncliff Rusty',
  'DAH-FCR-009',
  'Dusty rose with hints of coral and plum center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/fc-rusty.jpg',
  'varieties/legacy/fc-rusty.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8c7d3cb1-0c2d-49d7-b7cc-69e896245656',
  'ferncliff-spice',
  'Ferncliff Spice',
  'DAH-FCS-010',
  'Muted peach and honey blend.',
  600,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/fc-spice.jpg',
  'varieties/legacy/fc-spice.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'bd15ab60-7cac-4773-aaf6-530697de3d73',
  'fidalgo-blacky',
  'Fidalgo Blacky',
  'DAH-FDB-038',
  'Deep, velvety rich cranberry/black.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/fidalgo-blacky.jpg',
  'varieties/legacy/fidalgo-blacky.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8729e808-441e-4c09-972b-9605f579a7ef',
  'fluffles',
  'Fluffles',
  'DAH-FLF-027',
  'Lavender-pink with soft white center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/fluffles.jpg',
  'varieties/legacy/fluffles.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'dc7e9c0d-4dbe-476e-890d-39ef0cdf99ba',
  'gabbies-wish',
  'Gabby''s Wish',
  'DAH-GBW-039',
  'Soft coral-pink and yellow blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/gabbies-wish.jpg',
  'varieties/legacy/gabbies-wish.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b5b6716e-2abb-4dad-b3e9-1e21d27d7526',
  'gitts-attention',
  'Gitts Attention',
  'DAH-NEW-116',
  'Creamy white, fimbriated (fringed) petals.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1ff3cc55-8739-48d8-aed7-2cd3d8a8fa5c',
  'ice-tea',
  'Ice Tea',
  'DAH-ICT-040',
  'Sorbet orange fading to cream (ombre).',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/ice-tea.jpg',
  'varieties/legacy/ice-tea.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '898ba4a5-732b-478b-90dd-4a5ea49f3c22',
  'irish-d-porter',
  'Irish D. Porter',
  'DAH-IDP-018',
  'Blush pink with cream/yellow center (Pompon).',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/irish-d-porter.jpg',
  'varieties/legacy/irish-d-porter.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd0e1a1e1-0d0e-421a-b6a0-516b5b815fc6',
  'irish-ruffles',
  'Irish Ruffles',
  'DAH-NEW-117',
  'Pure white with a hint of blush.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/irish-ruffles.jpg',
  'varieties/legacy/irish-ruffles.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1f014486-ce16-440a-87f2-f5fc6d0253fd',
  'isabel',
  'Isabel',
  'DAH-ISB-019',
  'Lavender/mauve with dusty rose accents.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/isabel.jpg',
  'varieties/legacy/isabel.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd1710cd7-f0ff-46e2-914f-185905b5e086',
  'jowey-linda',
  'Jowey Linda',
  'DAH-JWL-006',
  'Warm apricot-orange.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '5-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/jowey-linda.jpg',
  'varieties/legacy/jowey-linda.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b56bc72b-9efb-4005-85d8-913cc9c51b50',
  'jowey-nicky',
  'Jowey Nicky',
  'DAH-JWN-041',
  'Peachy apricot.',
  0,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/jowey-nicky.jpg',
  'varieties/legacy/jowey-nicky.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '32536fda-a18b-471d-a39e-0cecabd5626e',
  'just-peachy',
  'Just Peachy',
  'DAH-JSP-042',
  'Peachy orange with hints of fuchsia.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/just-peachy.jpg',
  'varieties/legacy/just-peachy.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3ce77a42-9b8c-4220-9efd-cd59e4d4c961',
  'ka-cloud',
  'KA Cloud',
  'DAH-NEW-119',
  'White with very pale purple/yellow tints.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2ab81f9e-dca9-4f50-aa76-13fa123eb19e',
  'ka-mocha-katie',
  'KA Mocha Katie',
  'DAH-KMK-011',
  'Apricot/champagne with raspberry brushings.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/ka-mocha-katie.jpg',
  'varieties/legacy/ka-mocha-katie.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '092c4ff4-a8e1-48c4-ae7d-a96848c34d85',
  'ka-rosie-jo',
  'KA Rosie Jo',
  'DAH-NEW-120',
  'Smoky pink with raspberry accents.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/ka-rosie-jo.jpg',
  'varieties/legacy/ka-rosie-jo.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '335cb876-9df4-4448-b8f0-49cef6512f2a',
  'karma-chocolate',
  'Karma Chocolate',
  'DAH-KCH-012',
  'Dark chocolate shading to velvet red.',
  1200,
  NULL,
  'sold-out',
  'waterlily',
  '["red","dark-red"]',
  '4-5 inches',
  '3 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/karma-chocolate.jpg',
  'varieties/legacy/karma-chocolate.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'cfc06e21-66e7-4ff3-b9c6-191f8514d48c',
  'kelgai-ann',
  'Kelgai Ann',
  'DAH-NEW-121',
  'Soft pale pink with darker streaks.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f302f606-b849-431d-a346-1d0ce09ad95d',
  'koko-puff',
  'Koko Puff',
  'DAH-NEW-122',
  'Smoky mauve with lavender and tan undertones.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f6b977e9-5e49-4892-9735-cfa5748b0d62',
  'labyrinth',
  'Labyrinth',
  'DAH-LAB-013',
  'Vibrant mix of peach, apricot, and raspberry.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/labyrinth.jpg',
  'varieties/legacy/labyrinth.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '65a56e26-6a97-4d6d-98c2-a68c05675fff',
  'larks-ebbe',
  'Lark''s Ebbe',
  'DAH-NEW-123',
  'Pastel orange/apricot with yellow hints.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '22008c8e-02f5-4ca5-a827-6f75acb38e60',
  'last-dance',
  'Last Dance',
  'DAH-LSD-020',
  'White/lavender blend with purple pinstripes.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '5-6 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/last-dance.jpg',
  'varieties/legacy/last-dance.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '436dec2a-afff-4768-b980-e058c5e5e3f4',
  'miss-sarah',
  'Miss Sarah',
  'DAH-MSS-017',
  'Pink and cream ombre.',
  1000,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '3-4 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/miss-sarah.jpg',
  'varieties/legacy/miss-sarah.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1d8c5707-cd88-47f5-96c1-be8bb04f0c89',
  'mystique',
  'Mystique',
  'DAH-MYS-021',
  'Deep coral, pink, and red blend.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5-6 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/mystique.jpg',
  'varieties/legacy/mystique.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '746df410-4bd7-4a91-8ee6-0bf54aa28128',
  'nuit-dete',
  'N''uit D''ete',
  'DAH-NDE-043',
  'Dark black-burgundy (Cactus form).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/nuit-dete.jpg',
  'varieties/legacy/nuit-dete.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c270290e-09d8-4515-bc51-66712f3f68fa',
  'orange-globe',
  'Orange Globe',
  'DAH-ORG-044',
  'Dusty rose with warm bronze undertones.',
  2000,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/orange-globe.jpg',
  'varieties/legacy/orange-globe.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '31e84f22-a6ae-4dd5-ba3b-72009a8a716a',
  'parkland-tribute',
  'Parkland Tribute',
  'DAH-NEW-125',
  'Glowing salmon-coral.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '7c4089c9-4c65-4c27-9cd5-44caee93c7ae',
  'penhill-dark-monarch',
  'Penhill Dark Monarch',
  'DAH-PDM-014',
  'Dark burgundy-red with purple nuances.',
  1200,
  NULL,
  'sold-out',
  'dinnerplate',
  '["red","dark-red"]',
  '8-10 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/penhill-dark-monarch.jpg',
  'varieties/legacy/penhill-dark-monarch.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '83e54c41-94bf-45f4-a941-f44a5d0917d7',
  'petras-wedding',
  'Petra''s Wedding',
  'DAH-PTW-015',
  'White and cream ball.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '2-3 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/petras-wedding.jpg',
  'varieties/legacy/petras-wedding.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f41c060f-bf40-47d3-a502-cd27fd42c9a7',
  'pink-pearl',
  'Pink Pearl',
  'DAH-PKP-045',
  'Blush pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/pink-pearl.jpg',
  'varieties/legacy/pink-pearl.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '473eab55-2692-410e-a78a-83ef1aa8fa06',
  'platinum-blonde',
  'Platinum Blonde',
  'DAH-PLB-046',
  'White petals with fuzzy yellow center (Anemone).',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/platinum blonde.jpg',
  'varieties/legacy/platinum blonde.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c5908a98-1f8b-41da-9d8c-84433157d7f3',
  'polka',
  'Polka',
  'DAH-NEW-127',
  'Creamy white with deep pink edges/picotee.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f10cff86-12c8-475d-9cd1-b9bcd22a6535',
  'pooh',
  'Pooh',
  'DAH-POH-047',
  'Bright red with yellow tips (Collarette).',
  0,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/pooh.jpg',
  'varieties/legacy/pooh.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6cc70a9f-aa94-42eb-8819-a59c440a2072',
  'r-joan',
  'R Joan',
  'DAH-NEW-128',
  'Pink, peach, and soft apricot watercolor blend.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '70df57ec-aa6c-4ffa-9a26-158293ec4bdd',
  'rock-run-ashley',
  'Rock Run Ashley',
  'DAH-RRA-048',
  'Peachy pink to pale peach.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/rock-run-ashley.jpg',
  'varieties/legacy/rock-run-ashley.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '32342b2f-7b36-4e09-993e-b4086f8f8124',
  'rossendale-peach',
  'Rossendale Peach',
  'DAH-NEW-129',
  'Clear orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '97c3f57f-ec3d-415a-ab67-6c2b04adb4d2',
  'salish-twilight-girl',
  'Salish Twilight Girl',
  'DAH-NEW-130',
  'Smoky lavender with dark wine-purple outer petals.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2da32f65-5731-450b-bfc1-65691f43e894',
  'seniors-hope',
  'Senior''s Hope',
  'DAH-SNH-049',
  'Silvery mauve with rich plum reverse.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/seniors-hope.jpg',
  'varieties/legacy/seniors-hope.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ae47c827-29d9-47b3-9d12-e1d808b5971a',
  'sheer-heaven',
  'Sheer Heaven',
  'DAH-SHH-050',
  'Salmon-pink to pale peach-orange.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/sheer-heaven.jpg',
  'varieties/legacy/sheer-heaven.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '334c07c3-6b26-44be-abd0-82ef9c8fbf03',
  'snoho-doris',
  'Snoho Doris',
  'DAH-SND-051',
  'Orange and yellow blend (sometimes flecked).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/snoho-doris.jpg',
  'varieties/legacy/snoho-doris.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ec0ace62-afdd-410f-bcd3-0072225d4006',
  'snoho-sonia',
  'Snoho Sonia',
  'DAH-NEW-131',
  'Soft lavender-pink.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/snoho-sonia.jpg',
  'varieties/legacy/snoho-sonia.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'fa6b8ad4-adbe-4c05-801c-554a445277d5',
  'strawberries-n-cream',
  'Strawberries n Cream',
  'DAH-SNC-022',
  'Creamy white brushed with pink and red.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '3-4 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/strawberry-cream.jpg',
  'varieties/legacy/strawberry-cream.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e63a784a-ddd8-4baf-be5b-53993daebda1',
  'sweet-natalie',
  'Sweet Nathalie',
  'DAH-SWN-016',
  'Very pale pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3.5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/sweet-natalie.jpg',
  'varieties/legacy/sweet-natalie.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e30a98fa-a612-40b9-bcdd-1aa1c2e04050',
  'tempest',
  'Tempest',
  'DAH-NEW-132',
  'Warm coral-raspberry dusted with lavender.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1700fa0a-9b2e-4268-83f3-c005c764f20e',
  'terra-cotta',
  'Terra Cotta',
  'DAH-NEW-133',
  'Warm amber/butterscotch.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c24ca00b-255f-4352-810d-d98f131aa45d',
  'tiny-treasure',
  'Tiny Treasure',
  'DAH-NEW-134',
  'Ivory/White pompon.',
  1000,
  NULL,
  'sold-out',
  'pompon',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/placeholder-variety.jpg',
  'varieties/legacy/placeholder-variety.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '09439f77-1188-49ad-a35a-035c37879a9e',
  'valley-rust-bucket',
  'Valley Rust Bucket',
  'DAH-VRB-052',
  'Bright orange, copper, and rust.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/valley-rust-bucket.jpg',
  'varieties/legacy/valley-rust-bucket.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f8b0b16f-c0d6-4f9d-8065-7d98fdc501ac',
  'valley-tawney',
  'Valley Tawney',
  'DAH-NEW-135',
  'Peachy orange, honey yellow, and rose blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/valley-tawney.jpg',
  'varieties/legacy/valley-tawney.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '42b54bd5-529c-40c2-bee8-413dae416b52',
  'venus',
  'Venus',
  'DAH-VEN-023',
  'Soft peachy-orange (Orchette form).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '5-6 inches',
  '4-5 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/venus.jpg',
  'varieties/legacy/venus.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '75762df9-3670-412f-935c-bdcbc652f38d',
  'wd-brittany',
  'WD Brittany',
  'DAH-WDB-053',
  'Coral pink with gold blush.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/wd-brittany.jpg',
  'varieties/legacy/wd-brittany.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a5c77296-0baf-4267-8637-3d3af577cb6a',
  'wine-eyed-jill',
  'Wine Eyed Jill',
  'DAH-WEJ-024',
  'Cream, peach, and pink blend with dark eye.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '4-5 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/win-eyed-jill.jpg',
  'varieties/legacy/win-eyed-jill.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'db9efc83-a1f7-4ebf-a367-9f70a16bde27',
  'yelno-harmony',
  'Yelno Harmony',
  'DAH-YEH-025',
  'Warm apricot, peach, and buttery yellow.',
  1400,
  NULL,
  'sold-out',
  'waterlily',
  '["peach","salmon"]',
  '4-5 inches',
  '4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/yelno-harmony.jpg',
  'varieties/legacy/yelno-harmony.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '24da37bc-95b8-4cfb-ba92-9419c7481e31',
  'yvonne',
  'Yvonne',
  'DAH-YVN-054',
  'Soft pink/white blend (Waterlily form).',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  'https://opheliasflowers.ca/catalog-images/varieties/legacy/yvonne.jpg',
  'varieties/legacy/yvonne.jpg',
  0,
  '2026-03-20T00:22:59.131Z',
  '2026-03-20T00:22:59.131Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  updated_at = excluded.updated_at;
