INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6ca07943-5d08-4358-a33b-d2a4ecfc70b6',
  '20th-avenue-memory',
  '20th Avenue Memory',
  'DAH-TAM-028',
  'Soft blush-pink with a creamy center.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/20th-avenue-memory.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b676d409-5f77-4b19-acaf-07f36e48b2b4',
  'a-la-mode',
  'A La Mode',
  'DAH-ALM-029',
  'Striking orange with distinct white tips.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/a-la-mode.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9b200fb9-f44d-4708-a6f9-8d8f9c958ce2',
  'american-dawn',
  'American Dawn',
  'DAH-AMD-030',
  'Deep coral-orange with purple/magenta center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/american-dawn.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a6a80b4d-eaca-4842-a556-b6cd542306f7',
  'apple-blossom',
  'Apple Blossom',
  'DAH-APB-001',
  'Creamy yellow with soft blush pink edges.',
  1200,
  NULL,
  'sold-out',
  'collarette',
  '["pink","blush"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/apple-blossom.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '0ca1e8e0-c3c8-4565-b0ec-5edd79d7c215',
  'blizzard',
  'Blizzard',
  'DAH-NEW-101',
  'Pure white with a delicate dusting of ivory.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/blizzard.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '20a10975-6856-410d-9ee6-9fb9abc9e839',
  'bloomquist-alan',
  'Bloomquist Alan',
  'DAH-BQA-002',
  'Peachy-pink blend.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  '/catalog-seed/bq-alan.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '7a2bbd01-6cb6-4dc1-9e71-8413ffbc5147',
  'bloomquist-jean',
  'Bloomquist Jean',
  'DAH-BJN-032',
  'Vivid coppery-orange fading to sunset tones.',
  2200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bq-jean.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9b9f446e-fe2a-4e52-8aed-8a783a3a9ed9',
  'bloomquist-mojo',
  'Bloomquist Mojo',
  'DAH-BQM-003',
  'Deep vibrant pink with hints of yellow/orange.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5 inches',
  '5 feet',
  '/catalog-seed/bq-mojo.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'cac8fa01-751d-4292-8e9b-5aeac07795a6',
  'bloomquist-tory-p',
  'Bloomquist Tory P',
  'DAH-BTP-033',
  'Soft blush with lavender-pink centers.',
  2500,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bq-tory-p.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8e541ae4-2b09-4892-b68e-72212ff4ef5e',
  'bocherell',
  'Bocherell',
  'DAH-BOC-114',
  'A workhorse in the garden. Pumps out flowers until frost. Soft butter yellow with a hint of blush.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["yellow"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/bocherell.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c08913e3-168a-4395-9938-7d94266ca33c',
  'boom-boom-white',
  'Boom Boom White',
  'DAH-BBW-031',
  'Large white with a creamy center.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/boom-boom-white.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '27f209fb-d5a8-4520-b939-1fe7a131d317',
  'bracken-palomino',
  'Bracken Palomino',
  'DAH-NEW-102',
  'Bronze base with soft peachy accents.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '67b949f6-d6df-4097-99e5-4ee0dfe5924f',
  'bracken-rose',
  'Bracken Rose',
  'DAH-BKR-004',
  'Exquisite dusty rose ("ballet slipper pink").',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4 inches',
  '3-4 feet',
  '/catalog-seed/bracken-rose.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'cbf256b2-3b34-433a-aadb-84b2433f801c',
  'bracken-sarah',
  'Bracken Sarah',
  'DAH-NEW-103',
  'Creamy golden yellow with peach highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b1d1dcb0-076d-4ede-b260-396798d954f0',
  'bride-to-be',
  'Bride to Be',
  'DAH-NEW-104',
  'Pure white with a hint of pale yellow at the center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bride-to-be.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '78576e7b-1a1a-469b-9517-0ce0be34c8e6',
  'brown-sugar',
  'Brown Sugar',
  'DAH-NEW-105',
  'Rusty orange with reddish center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/brown-sugar.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3b045a8a-dfb9-494e-86fa-1d4ff7d6032f',
  'budapest-blush',
  'Budapest Blush',
  'DAH-NEW-106',
  'Soft pink, occasionally with white.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1a74989c-ea46-4067-98b3-7287a27d6e4f',
  'cafe-au-lait',
  'Cafe Au Lait',
  'DAH-NEW-107',
  'Famous cream/blush/beige shift; very variable.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1957833d-4b03-49ea-a390-d0fd0f0d71f7',
  'caitlynns-joy',
  'Caitlynns Joy',
  'DAH-NEW-108',
  'Hot pink/purple with apricot highlights.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e9c60b7c-eb91-4339-a10a-8027b0497a97',
  'cal-mini',
  'Café au Lait Mini',
  'DAH-CLM-005',
  'Creamy blush/pink (smaller Cafe Au Lait type).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '3-5 inches',
  '4 feet',
  '/catalog-seed/CAL-mini.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4eed230f-404d-4446-a0a3-cd6fe4d4faf4',
  'castle-drive',
  'Castle Drive',
  'DAH-CSD-007',
  'Soft blush-pink with yellow highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/castle-drive.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2247cf7c-449a-4bc2-a86c-58801806fb13',
  'chewy',
  'Chewy',
  'DAH-CHW-034',
  'Peachy buff with a lavender dusting (bronzed look).',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/chewy.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd5e71cd0-5845-4459-8ae4-e2e518285cac',
  'clearview-peachy',
  'Clearview Peachy',
  'DAH-CLP-035',
  'Muted peachy-pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/clearview-peachy.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd0871c9b-0ad4-4032-91bf-85d1d95b1dfc',
  'colorado-classic',
  'Colorado Classic',
  'DAH-NEW-109',
  'Ivory petals edged with vivid candy-pink.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e9ffec84-519d-400e-a1d7-bdf60c9c327c',
  'copper-boy',
  'Copper Boy',
  'DAH-NEW-110',
  'Glowing copper, bronze, and burnt orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '51f539ee-1264-4d62-8e2f-4a1e152504c8',
  'coralie',
  'Coralie',
  'DAH-COR-008',
  'Soft blush pink with subtle lavender tones.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/coralie.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9580755f-079a-4950-b802-a8749e2d0273',
  'cornel-bronze',
  'Cornel Bronze',
  'DAH-NEW-112',
  'Rich bronze and copper.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '71ead0ad-f600-48eb-9c72-1de664525d4b',
  'cornel',
  'Cornel',
  'DAH-NEW-111',
  'Dark cherry-red ball.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/cornel.png',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5895db2c-6744-45f5-b4a3-8bbd23ab3ac7',
  'coseytown-bounty',
  'Coseytown Bounty',
  'DAH-NEW-113',
  'Peachy-orange with golden hues.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ad8101c9-772e-49b5-82ed-f4af8d9b205e',
  'creamy',
  'Creamy',
  'DAH-CRM-026',
  'Soft butter yellow.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/creamy.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9ce8ea21-2079-44f8-afae-17ac54ae89c8',
  'creme-de-cassis',
  'Crème De Cassis',
  'DAH-CDK-036',
  'Lavender/mauve top with dark berry/wine reverse.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/creme-de-cassis.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8174bae9-8401-41cd-b7c9-ae0f96fc82af',
  'crighton-honey',
  'Crichton Honey',
  'DAH-CRH-037',
  'Blend of creamy lemon, soft peach, and apricot.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/crighton-honey.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6e77d1e7-25ff-486d-9962-1b3c347a062a',
  'diva',
  'Diva',
  'DAH-DIV-114',
  'Deep velvety purple to dark raspberrry.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/diva.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'da3b8f69-ae14-4530-bada-1d49bb978fc6',
  'eveline',
  'Eveline',
  'DAH-NEW-114',
  'White with faint lavender tips/center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5cff7525-56fd-487e-949b-b5112cddde32',
  'ferncliff-copper',
  'Ferncliff Copper',
  'DAH-NEW-115',
  'Soft copper-orange with yellow accents.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ef4df3e7-a592-4d49-9134-6b05d0ee9ce0',
  'ferncliff-rusty',
  'Ferncliff Rusty',
  'DAH-FCR-009',
  'Dusty rose with hints of coral and plum center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '4 feet',
  '/catalog-seed/fc-rusty.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '17f3ba17-31a8-4d72-afa2-aa849abce050',
  'ferncliff-spice',
  'Ferncliff Spice',
  'DAH-FCS-010',
  'Muted peach and honey blend.',
  600,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '5 inches',
  '4 feet',
  '/catalog-seed/fc-spice.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a6d25611-cbd7-4b9c-a4d1-03dccda2adb4',
  'fidalgo-blacky',
  'Fidalgo Blacky',
  'DAH-FDB-038',
  'Deep, velvety rich cranberry/black.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/fidalgo-blacky.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ae70a7dc-7508-4c11-b1b8-33b4134fcf51',
  'fluffles',
  'Fluffles',
  'DAH-FLF-027',
  'Lavender-pink with soft white center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3-4 feet',
  '/catalog-seed/fluffles.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '27664c8d-00c2-4eac-9fbf-849a07d3f301',
  'gabbies-wish',
  'Gabby''s Wish',
  'DAH-GBW-039',
  'Soft coral-pink and yellow blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/gabbies-wish.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '12a5325b-0dcf-42fe-b5bb-b95517fcb104',
  'gitts-attention',
  'Gitts Attention',
  'DAH-NEW-116',
  'Creamy white, fimbriated (fringed) petals.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '20dfb73a-48cf-4ba3-a3c0-cd8e3cff3cc2',
  'ice-tea',
  'Ice Tea',
  'DAH-ICT-040',
  'Sorbet orange fading to cream (ombre).',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/ice-tea.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd4f1eaef-f518-42c9-9200-2b1af5a9ccd1',
  'irish-d-porter',
  'Irish D. Porter',
  'DAH-IDP-018',
  'Blush pink with cream/yellow center (Pompon).',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/irish-d-porter.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e346565c-5257-42eb-8f21-2729381fbcfb',
  'irish-ruffles',
  'Irish Ruffles',
  'DAH-NEW-117',
  'Pure white with a hint of blush.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/irish-ruffles.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f12678c1-8303-4987-b801-9b74576cf58a',
  'isabel',
  'Isabel',
  'DAH-ISB-019',
  'Lavender/mauve with dusty rose accents.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/isabel.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '0fde7a39-a72e-4a73-825c-64243c7095e4',
  'jowey-linda',
  'Jowey Linda',
  'DAH-JWL-006',
  'Warm apricot-orange.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '5-6 inches',
  '3-4 feet',
  '/catalog-seed/jowey-linda.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '42c17e11-542c-4014-8d45-0f5790ae078d',
  'jowey-nicky',
  'Jowey Nicky',
  'DAH-JWN-041',
  'Peachy apricot.',
  0,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/jowey-nicky.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '46373290-c8f3-4908-a55f-a50148be2baa',
  'just-peachy',
  'Just Peachy',
  'DAH-JSP-042',
  'Peachy orange with hints of fuchsia.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/just-peachy.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c4a6ab0a-d9ed-4bf5-af29-55223b4192c5',
  'ka-cloud',
  'KA Cloud',
  'DAH-NEW-119',
  'White with very pale purple/yellow tints.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b322c939-1474-489f-a52a-a1b8460eeeab',
  'ka-mocha-katie',
  'KA Mocha Katie',
  'DAH-KMK-011',
  'Apricot/champagne with raspberry brushings.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4 inches',
  '3-4 feet',
  '/catalog-seed/ka-mocha-katie.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6fd830b8-ba3d-40b7-b023-465cb0d6a949',
  'ka-rosie-jo',
  'KA Rosie Jo',
  'DAH-NEW-120',
  'Smoky pink with raspberry accents.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/ka-rosie-jo.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '766e4104-b1ae-46e4-9276-01d631a689c5',
  'karma-chocolate',
  'Karma Chocolate',
  'DAH-KCH-012',
  'Dark chocolate shading to velvet red.',
  1200,
  NULL,
  'sold-out',
  'waterlily',
  '["red","dark-red"]',
  '4-5 inches',
  '3 feet',
  '/catalog-seed/karma-chocolate.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9794490b-0935-4b7a-abec-7c01b08078fa',
  'kelgai-ann',
  'Kelgai Ann',
  'DAH-NEW-121',
  'Soft pale pink with darker streaks.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2df50011-1417-449e-8e35-040e69cf94f7',
  'koko-puff',
  'Koko Puff',
  'DAH-NEW-122',
  'Smoky mauve with lavender and tan undertones.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '26ae10d8-b45f-4303-bc3c-a2a6f7775466',
  'labyrinth',
  'Labyrinth',
  'DAH-LAB-013',
  'Vibrant mix of peach, apricot, and raspberry.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  '/catalog-seed/labyrinth.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '0e847688-6475-40bb-8fd2-72dcda30886a',
  'larks-ebbe',
  'Lark''s Ebbe',
  'DAH-NEW-123',
  'Pastel orange/apricot with yellow hints.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '28af88fa-24fa-46a9-82b9-f145bc9d30b1',
  'last-dance',
  'Last Dance',
  'DAH-LSD-020',
  'White/lavender blend with purple pinstripes.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '5-6 inches',
  '4-5 feet',
  '/catalog-seed/last-dance.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e7c1e5a3-9a19-4703-8863-2453e48dbe90',
  'miss-sarah',
  'Miss Sarah',
  'DAH-MSS-017',
  'Pink and cream ombre.',
  1000,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '3-4 inches',
  '4 feet',
  '/catalog-seed/miss-sarah.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5d484555-87d5-4a7f-9f72-cdbc45cd9a38',
  'mystique',
  'Mystique',
  'DAH-MYS-021',
  'Deep coral, pink, and red blend.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5-6 inches',
  '4 feet',
  '/catalog-seed/mystique.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '417ac40f-f921-45d2-99d6-bd378d4529e4',
  'nuit-dete',
  'N''uit D''ete',
  'DAH-NDE-043',
  'Dark black-burgundy (Cactus form).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/nuit-dete.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2c7e6a9f-71af-421b-9ed2-9a240e74b976',
  'orange-globe',
  'Orange Globe',
  'DAH-ORG-044',
  'Dusty rose with warm bronze undertones.',
  2000,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/orange-globe.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '958b46e0-b368-4e51-bdca-7bb4da9d08f8',
  'parkland-tribute',
  'Parkland Tribute',
  'DAH-NEW-125',
  'Glowing salmon-coral.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '0e542c76-b608-48d0-8c71-a1bec45446b8',
  'penhill-dark-monarch',
  'Penhill Dark Monarch',
  'DAH-PDM-014',
  'Dark burgundy-red with purple nuances.',
  1200,
  NULL,
  'sold-out',
  'dinnerplate',
  '["red","dark-red"]',
  '8-10 inches',
  '4-5 feet',
  '/catalog-seed/penhill-dark-monarch.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e4859c07-dc2c-447c-9bf8-7345b6e4a78d',
  'petras-wedding',
  'Petra''s Wedding',
  'DAH-PTW-015',
  'White and cream ball.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '2-3 inches',
  '4-5 feet',
  '/catalog-seed/petras-wedding.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a7c9cf42-92ff-4c4b-896b-fe4b3a97d8c6',
  'pink-pearl',
  'Pink Pearl',
  'DAH-PKP-045',
  'Blush pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/pink-pearl.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ce62aa0f-b2f6-4f82-8835-f1dd9d6d3e86',
  'platinum-blonde',
  'Platinum Blonde',
  'DAH-PLB-046',
  'White petals with fuzzy yellow center (Anemone).',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/platinum blonde.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '96edca7e-d386-43af-ac64-580fcd9c50b9',
  'polka',
  'Polka',
  'DAH-NEW-127',
  'Creamy white with deep pink edges/picotee.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '75bc83f0-36d1-4baf-a00d-847822484006',
  'pooh',
  'Pooh',
  'DAH-POH-047',
  'Bright red with yellow tips (Collarette).',
  0,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/pooh.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b75d0522-a854-41d9-be30-f98cab4795ed',
  'r-joan',
  'R Joan',
  'DAH-NEW-128',
  'Pink, peach, and soft apricot watercolor blend.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5bbb82b0-8304-46b5-a7c8-0775b2b0c55a',
  'rock-run-ashley',
  'Rock Run Ashley',
  'DAH-RRA-048',
  'Peachy pink to pale peach.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/rock-run-ashley.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9c2af188-150a-490d-9372-ee204b0ee65a',
  'rossendale-peach',
  'Rossendale Peach',
  'DAH-NEW-129',
  'Clear orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e2ea86e0-f130-4da6-b984-a33049dc5c2c',
  'salish-twilight-girl',
  'Salish Twilight Girl',
  'DAH-NEW-130',
  'Smoky lavender with dark wine-purple outer petals.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd75e50fa-b230-4c44-b89a-36ba96c1bdab',
  'seniors-hope',
  'Senior''s Hope',
  'DAH-SNH-049',
  'Silvery mauve with rich plum reverse.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/seniors-hope.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '64a6861c-5dee-40e2-9bba-d38f4795adbc',
  'sheer-heaven',
  'Sheer Heaven',
  'DAH-SHH-050',
  'Salmon-pink to pale peach-orange.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/sheer-heaven.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8c2e880f-7a2c-4b7f-8cf1-8c6013471544',
  'snoho-doris',
  'Snoho Doris',
  'DAH-SND-051',
  'Orange and yellow blend (sometimes flecked).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/snoho-doris.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e2311d2d-f9a3-460b-8e81-f7df33489107',
  'snoho-sonia',
  'Snoho Sonia',
  'DAH-NEW-131',
  'Soft lavender-pink.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/snoho-sonia.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '0801d999-e571-4b17-a644-fe1604154480',
  'strawberries-n-cream',
  'Strawberries n Cream',
  'DAH-SNC-022',
  'Creamy white brushed with pink and red.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/strawberry-cream.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '71ff70af-b1fc-4f4b-8775-6fa1a0f281a3',
  'sweet-natalie',
  'Sweet Nathalie',
  'DAH-SWN-016',
  'Very pale pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3.5 feet',
  '/catalog-seed/sweet-natalie.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a3e9286c-f2c6-4cbf-b14a-21b20263485d',
  'tempest',
  'Tempest',
  'DAH-NEW-132',
  'Warm coral-raspberry dusted with lavender.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '315b9269-c4bf-474d-8b50-e5f647d106bf',
  'terra-cotta',
  'Terra Cotta',
  'DAH-NEW-133',
  'Warm amber/butterscotch.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c6dfbbd4-e5d2-49a8-ae8d-3a96b50f1a48',
  'tiny-treasure',
  'Tiny Treasure',
  'DAH-NEW-134',
  'Ivory/White pompon.',
  1000,
  NULL,
  'sold-out',
  'pompon',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '00487937-cd42-4069-a185-e9bfe6ed1db4',
  'valley-rust-bucket',
  'Valley Rust Bucket',
  'DAH-VRB-052',
  'Bright orange, copper, and rust.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/valley-rust-bucket.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'fd8c8f69-cac7-4d6a-b102-2e698d10de49',
  'valley-tawney',
  'Valley Tawney',
  'DAH-NEW-135',
  'Peachy orange, honey yellow, and rose blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/valley-tawney.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '992b47ba-345c-4301-9cd6-579e6c24627e',
  'venus',
  'Venus',
  'DAH-VEN-023',
  'Soft peachy-orange (Orchette form).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '5-6 inches',
  '4-5 feet',
  '/catalog-seed/venus.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ff91a5df-85ba-41e3-bb70-3c9600526a64',
  'wd-brittany',
  'WD Brittany',
  'DAH-WDB-053',
  'Coral pink with gold blush.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/wd-brittany.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c7d4d628-6d1e-49e3-89e7-0d1f1271797e',
  'wine-eyed-jill',
  'Wine Eyed Jill',
  'DAH-WEJ-024',
  'Cream, peach, and pink blend with dark eye.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '4-5 inches',
  '3-4 feet',
  '/catalog-seed/win-eyed-jill.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c58ac50d-049c-45a0-b171-e980b58e7095',
  'yelno-harmony',
  'Yelno Harmony',
  'DAH-YEH-025',
  'Warm apricot, peach, and buttery yellow.',
  1400,
  NULL,
  'sold-out',
  'waterlily',
  '["peach","salmon"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/yelno-harmony.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4cd70799-9ddc-4bac-9fe1-ee0240df7508',
  'yvonne',
  'Yvonne',
  'DAH-YVN-054',
  'Soft pink/white blend (Waterlily form).',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/yvonne.jpg',
  NULL,
  0,
  '2026-03-21T03:11:47.503Z',
  '2026-03-21T03:11:47.503Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;
