INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1a68ae80-8077-4990-9faa-daebdf4b5a91',
  '20th-avenue-memory',
  '20th Avenue Memory',
  'DAH-TAM-028',
  'Soft blush-pink with a creamy center.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/20th-avenue-memory.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2c9f9edc-ecf1-4680-909d-659b0d149c87',
  'a-la-mode',
  'A La Mode',
  'DAH-ALM-029',
  'Striking orange with distinct white tips.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/a-la-mode.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'bde41b23-2cd1-42be-8e65-19a15fdfcd98',
  'american-dawn',
  'American Dawn',
  'DAH-AMD-030',
  'Deep coral-orange with purple/magenta center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/american-dawn.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a47d4af0-1e35-4209-8e65-7da78ab9d28b',
  'apple-blossom',
  'Apple Blossom',
  'DAH-APB-001',
  'Creamy yellow with soft blush pink edges.',
  1200,
  NULL,
  'sold-out',
  'collarette',
  '["pink","blush"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/apple-blossom.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c9aa445e-ec20-465c-94ab-c8f57f3e152f',
  'blizzard',
  'Blizzard',
  'DAH-NEW-101',
  'Pure white with a delicate dusting of ivory.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/blizzard.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f162a940-98c2-4fc8-a89a-e7a920d7a5ff',
  'bloomquist-alan',
  'Bloomquist Alan',
  'DAH-BQA-002',
  'Peachy-pink blend.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  '/catalog-seed/bq-alan.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e47b074f-1376-48c1-a218-aa356fef608c',
  'bloomquist-jean',
  'Bloomquist Jean',
  'DAH-BJN-032',
  'Vivid coppery-orange fading to sunset tones.',
  2200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bq-jean.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9b22a696-5323-4112-868d-2dbd8e010cc3',
  'bloomquist-mojo',
  'Bloomquist Mojo',
  'DAH-BQM-003',
  'Deep vibrant pink with hints of yellow/orange.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5 inches',
  '5 feet',
  '/catalog-seed/bq-mojo.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '88f2e63b-f32b-4ec0-9cff-8189e78aa3b4',
  'bloomquist-tory-p',
  'Bloomquist Tory P',
  'DAH-BTP-033',
  'Soft blush with lavender-pink centers.',
  2500,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bq-tory-p.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '63c8b592-33e6-465e-9674-e538243e24c7',
  'bocherell',
  'Bocherell',
  'DAH-BOC-114',
  'A workhorse in the garden. Pumps out flowers until frost. Soft butter yellow with a hint of blush.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["yellow"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/bocherell.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2578b496-835e-4ed5-a77d-c58acd114797',
  'boom-boom-white',
  'Boom Boom White',
  'DAH-BBW-031',
  'Large white with a creamy center.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/boom-boom-white.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd4175002-72e0-4e01-b58a-36c13a787d7c',
  'bracken-palomino',
  'Bracken Palomino',
  'DAH-NEW-102',
  'Bronze base with soft peachy accents.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c6c3f5a7-9392-4898-a240-795647e9c2ec',
  'bracken-rose',
  'Bracken Rose',
  'DAH-BKR-004',
  'Exquisite dusty rose ("ballet slipper pink").',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4 inches',
  '3-4 feet',
  '/catalog-seed/bracken-rose.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f6370c53-f57e-4ef5-8480-1972c966ff04',
  'bracken-sarah',
  'Bracken Sarah',
  'DAH-NEW-103',
  'Creamy golden yellow with peach highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '78eb7ca3-898b-4565-a4b6-afdef09a1a1d',
  'bride-to-be',
  'Bride to Be',
  'DAH-NEW-104',
  'Pure white with a hint of pale yellow at the center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/bride-to-be.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a0bbb1e0-8f2e-4448-a5c8-6e5b85aadbbb',
  'brown-sugar',
  'Brown Sugar',
  'DAH-NEW-105',
  'Rusty orange with reddish center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/brown-sugar.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'fcd2a460-7c10-4cd4-ab22-5bb1f8e5ff7f',
  'budapest-blush',
  'Budapest Blush',
  'DAH-NEW-106',
  'Soft pink, occasionally with white.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f0f8e762-5600-4738-b32e-b0250e9935e7',
  'cafe-au-lait',
  'Cafe Au Lait',
  'DAH-NEW-107',
  'Famous cream/blush/beige shift; very variable.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1ab2e9a5-3073-48ae-91af-cacde48c75fe',
  'caitlynns-joy',
  'Caitlynns Joy',
  'DAH-NEW-108',
  'Hot pink/purple with apricot highlights.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8965fa2f-1008-4f9a-b345-58ebccd98bda',
  'cal-mini',
  'Café au Lait Mini',
  'DAH-CLM-005',
  'Creamy blush/pink (smaller Cafe Au Lait type).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '3-5 inches',
  '4 feet',
  '/catalog-seed/CAL-mini.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '471b0cd2-8013-4c64-bec0-41cce9080360',
  'castle-drive',
  'Castle Drive',
  'DAH-CSD-007',
  'Soft blush-pink with yellow highlights.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/castle-drive.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ed52220a-3481-4a8a-88a6-63e8265ce12d',
  'chewy',
  'Chewy',
  'DAH-CHW-034',
  'Peachy buff with a lavender dusting (bronzed look).',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/chewy.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6e606320-45fa-4099-9cde-fa37ca22ff10',
  'clearview-peachy',
  'Clearview Peachy',
  'DAH-CLP-035',
  'Muted peachy-pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/clearview-peachy.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '19ff87ac-9767-490a-99e6-35ae5b1dfe52',
  'colorado-classic',
  'Colorado Classic',
  'DAH-NEW-109',
  'Ivory petals edged with vivid candy-pink.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'adcb7403-574f-4598-b5d6-de78d7917ae5',
  'copper-boy',
  'Copper Boy',
  'DAH-NEW-110',
  'Glowing copper, bronze, and burnt orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c7d27ab4-7894-4622-8572-55aa7c4ba4c9',
  'coralie',
  'Coralie',
  'DAH-COR-008',
  'Soft blush pink with subtle lavender tones.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/coralie.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '7533378c-447a-4850-8ed1-334a676240b6',
  'cornel-bronze',
  'Cornel Bronze',
  'DAH-NEW-112',
  'Rich bronze and copper.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '86173dc4-2353-4097-98e2-00f254bae30a',
  'cornel',
  'Cornel',
  'DAH-NEW-111',
  'Dark cherry-red ball.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/cornel.png',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '6bc66a41-8deb-47c6-a589-149524150356',
  'coseytown-bounty',
  'Coseytown Bounty',
  'DAH-NEW-113',
  'Peachy-orange with golden hues.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd0519d80-82a2-4be8-9655-d53b86c8b8fc',
  'creamy',
  'Creamy',
  'DAH-CRM-026',
  'Soft butter yellow.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["cream","yellow"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/creamy.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '63415a58-f238-4023-8e21-e91654003be0',
  'creme-de-cassis',
  'Crème De Cassis',
  'DAH-CDK-036',
  'Lavender/mauve top with dark berry/wine reverse.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/creme-de-cassis.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3cdf80c6-d568-4d57-ab5f-65e8e010a028',
  'crighton-honey',
  'Crichton Honey',
  'DAH-CRH-037',
  'Blend of creamy lemon, soft peach, and apricot.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/crighton-honey.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '79c087a6-1ea7-41f1-88a4-2dccd5f17c6a',
  'diva',
  'Diva',
  'DAH-DIV-114',
  'Deep velvety purple to dark raspberrry.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/diva.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e254ebc4-090c-42bf-a10b-d475d4d00b3b',
  'eveline',
  'Eveline',
  'DAH-NEW-114',
  'White with faint lavender tips/center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '87c10531-d7b6-4487-9af6-d64e1daa1b43',
  'ferncliff-copper',
  'Ferncliff Copper',
  'DAH-NEW-115',
  'Soft copper-orange with yellow accents.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e57dc3d6-f0de-452a-9ddd-b7520fc8814a',
  'ferncliff-rusty',
  'Ferncliff Rusty',
  'DAH-FCR-009',
  'Dusty rose with hints of coral and plum center.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '4 feet',
  '/catalog-seed/fc-rusty.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'aa5e0d4e-d754-46a6-b8ae-8c70719ebf3f',
  'ferncliff-spice',
  'Ferncliff Spice',
  'DAH-FCS-010',
  'Muted peach and honey blend.',
  600,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '5 inches',
  '4 feet',
  '/catalog-seed/fc-spice.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '06f0c03e-7342-463d-babc-09bafe0bb42e',
  'fidalgo-blacky',
  'Fidalgo Blacky',
  'DAH-FDB-038',
  'Deep, velvety rich cranberry/black.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/fidalgo-blacky.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9f667a12-0083-4d06-a42f-e05da8dbd492',
  'fluffles',
  'Fluffles',
  'DAH-FLF-027',
  'Lavender-pink with soft white center.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3-4 feet',
  '/catalog-seed/fluffles.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd9337865-5d8f-4d27-83ce-bac71922c2c6',
  'gabbies-wish',
  'Gabby''s Wish',
  'DAH-GBW-039',
  'Soft coral-pink and yellow blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/gabbies-wish.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e65a087b-074c-4a29-b767-090f48fe97a5',
  'gitts-attention',
  'Gitts Attention',
  'DAH-NEW-116',
  'Creamy white, fimbriated (fringed) petals.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f128b6fe-20be-4ab2-a9f4-a0c3ea4527f4',
  'ice-tea',
  'Ice Tea',
  'DAH-ICT-040',
  'Sorbet orange fading to cream (ombre).',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/ice-tea.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b3e1119f-a1a1-4edc-9784-5f5447f2c7ae',
  'irish-d-porter',
  'Irish D. Porter',
  'DAH-IDP-018',
  'Blush pink with cream/yellow center (Pompon).',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/irish-d-porter.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '76c547e0-5f45-4987-80c8-5317690d3938',
  'irish-ruffles',
  'Irish Ruffles',
  'DAH-NEW-117',
  'Pure white with a hint of blush.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/irish-ruffles.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e6c9bcb3-4d8d-49d7-821d-f25d1846a9f4',
  'isabel',
  'Isabel',
  'DAH-ISB-019',
  'Lavender/mauve with dusty rose accents.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/isabel.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '401302fe-22db-4f8a-9ee3-23a59fd10bad',
  'jowey-linda',
  'Jowey Linda',
  'DAH-JWL-006',
  'Warm apricot-orange.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '5-6 inches',
  '3-4 feet',
  '/catalog-seed/jowey-linda.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1b7b95e2-97db-45e2-87b0-ddb557e09799',
  'jowey-nicky',
  'Jowey Nicky',
  'DAH-JWN-041',
  'Peachy apricot.',
  0,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/jowey-nicky.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4b274a2c-5942-4237-a57b-e869e0aec300',
  'just-peachy',
  'Just Peachy',
  'DAH-JSP-042',
  'Peachy orange with hints of fuchsia.',
  600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/just-peachy.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4d051fa6-b26b-4ac2-8d66-31f3a69f740a',
  'ka-cloud',
  'KA Cloud',
  'DAH-NEW-119',
  'White with very pale purple/yellow tints.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9756e8f4-4777-438d-8e89-1ba8e1b3474b',
  'ka-mocha-katie',
  'KA Mocha Katie',
  'DAH-KMK-011',
  'Apricot/champagne with raspberry brushings.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4 inches',
  '3-4 feet',
  '/catalog-seed/ka-mocha-katie.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5ec76415-7dde-407b-95d6-5dacf0be4db6',
  'ka-rosie-jo',
  'KA Rosie Jo',
  'DAH-NEW-120',
  'Smoky pink with raspberry accents.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/ka-rosie-jo.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3a6b93f6-d81d-43ee-836b-06d69c021040',
  'karma-chocolate',
  'Karma Chocolate',
  'DAH-KCH-012',
  'Dark chocolate shading to velvet red.',
  1200,
  NULL,
  'sold-out',
  'waterlily',
  '["red","dark-red"]',
  '4-5 inches',
  '3 feet',
  '/catalog-seed/karma-chocolate.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4b91ba93-c952-4fbb-b7da-f4f8007d128e',
  'kelgai-ann',
  'Kelgai Ann',
  'DAH-NEW-121',
  'Soft pale pink with darker streaks.',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'acebd4de-8f3f-4bd8-abe5-9811fbdf2840',
  'koko-puff',
  'Koko Puff',
  'DAH-NEW-122',
  'Smoky mauve with lavender and tan undertones.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd6f44bbf-5a90-4c2a-a4fc-33030d9e4c8c',
  'labyrinth',
  'Labyrinth',
  'DAH-LAB-013',
  'Vibrant mix of peach, apricot, and raspberry.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '6-8 inches',
  '4-5 feet',
  '/catalog-seed/labyrinth.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '958b9eb4-70d2-4e01-8da5-913912161513',
  'larks-ebbe',
  'Lark''s Ebbe',
  'DAH-NEW-123',
  'Pastel orange/apricot with yellow hints.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '234a2144-8ca7-4097-bba1-0a8cd1a7623f',
  'last-dance',
  'Last Dance',
  'DAH-LSD-020',
  'White/lavender blend with purple pinstripes.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '5-6 inches',
  '4-5 feet',
  '/catalog-seed/last-dance.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '9fbfd019-ba42-45c5-b869-61e66094c7e4',
  'miss-sarah',
  'Miss Sarah',
  'DAH-MSS-017',
  'Pink and cream ombre.',
  1000,
  NULL,
  'sold-out',
  'ball',
  '["pink","blush"]',
  '3-4 inches',
  '4 feet',
  '/catalog-seed/miss-sarah.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'dede1255-9956-4475-81d9-229a175cc8aa',
  'mystique',
  'Mystique',
  'DAH-MYS-021',
  'Deep coral, pink, and red blend.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '5-6 inches',
  '4 feet',
  '/catalog-seed/mystique.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'fb1fcb6a-d4fe-4c1c-9d23-793ce7141f53',
  'nuit-dete',
  'N''uit D''ete',
  'DAH-NDE-043',
  'Dark black-burgundy (Cactus form).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["red","dark-red"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/nuit-dete.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '58845599-bbd6-4f9c-af23-affccdb32457',
  'orange-globe',
  'Orange Globe',
  'DAH-ORG-044',
  'Dusty rose with warm bronze undertones.',
  2000,
  NULL,
  'sold-out',
  'ball',
  '["orange","bronze"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/orange-globe.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '561f5d1f-db1b-4621-84a3-7f63e98037b4',
  'parkland-tribute',
  'Parkland Tribute',
  'DAH-NEW-125',
  'Glowing salmon-coral.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '4cc5285d-9337-4ade-bc9e-a2d25508070d',
  'penhill-dark-monarch',
  'Penhill Dark Monarch',
  'DAH-PDM-014',
  'Dark burgundy-red with purple nuances.',
  1200,
  NULL,
  'sold-out',
  'dinnerplate',
  '["red","dark-red"]',
  '8-10 inches',
  '4-5 feet',
  '/catalog-seed/penhill-dark-monarch.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '20d6d34e-bbda-41a8-aaf4-9792f8d51645',
  'petras-wedding',
  'Petra''s Wedding',
  'DAH-PTW-015',
  'White and cream ball.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["white"]',
  '2-3 inches',
  '4-5 feet',
  '/catalog-seed/petras-wedding.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ac752e1a-ef12-4219-bada-a09e7dd0de86',
  'pink-pearl',
  'Pink Pearl',
  'DAH-PKP-045',
  'Blush pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/pink-pearl.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'f7b9195b-6aa9-4dfc-9945-e215ce3d1974',
  'platinum-blonde',
  'Platinum Blonde',
  'DAH-PLB-046',
  'White petals with fuzzy yellow center (Anemone).',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/platinum blonde.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ce09d7f8-f72c-4a9e-9a46-2f778cada521',
  'polka',
  'Polka',
  'DAH-NEW-127',
  'Creamy white with deep pink edges/picotee.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd02599f9-48da-468e-aeab-cf0018d17bf8',
  'pooh',
  'Pooh',
  'DAH-POH-047',
  'Bright red with yellow tips (Collarette).',
  0,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/pooh.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '7bfd366d-e177-4a46-b30b-f3e48ca65593',
  'r-joan',
  'R Joan',
  'DAH-NEW-128',
  'Pink, peach, and soft apricot watercolor blend.',
  2000,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '3e4e4c3f-05f3-4111-9574-155e25a7774f',
  'rock-run-ashley',
  'Rock Run Ashley',
  'DAH-RRA-048',
  'Peachy pink to pale peach.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/rock-run-ashley.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '52b7330d-43b3-41d4-8ffd-1e165b64c1cb',
  'rossendale-peach',
  'Rossendale Peach',
  'DAH-NEW-129',
  'Clear orange.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '8fd72231-81bc-4199-9f51-be5cd94238c5',
  'salish-twilight-girl',
  'Salish Twilight Girl',
  'DAH-NEW-130',
  'Smoky lavender with dark wine-purple outer petals.',
  1600,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '5985e176-cd23-4847-9f10-7cf98c1949d7',
  'seniors-hope',
  'Senior''s Hope',
  'DAH-SNH-049',
  'Silvery mauve with rich plum reverse.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/seniors-hope.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '68a39537-c8c4-4123-b493-e77a4f5996a7',
  'sheer-heaven',
  'Sheer Heaven',
  'DAH-SHH-050',
  'Salmon-pink to pale peach-orange.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/sheer-heaven.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'ea230e26-011a-400c-a558-0c757e22404d',
  'snoho-doris',
  'Snoho Doris',
  'DAH-SND-051',
  'Orange and yellow blend (sometimes flecked).',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/snoho-doris.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c9cfc93c-702f-4051-a609-58a39aafd24e',
  'snoho-sonia',
  'Snoho Sonia',
  'DAH-NEW-131',
  'Soft lavender-pink.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["lavender","purple"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/snoho-sonia.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e297a391-a1a3-4cc8-aca7-a385e7930e20',
  'strawberries-n-cream',
  'Strawberries n Cream',
  'DAH-SNC-022',
  'Creamy white brushed with pink and red.',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["bi-color","variegated"]',
  '3-4 inches',
  '3-4 feet',
  '/catalog-seed/strawberry-cream.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '1d1e641d-2efd-481c-bfaa-ddc8fa9c9aa8',
  'sweet-natalie',
  'Sweet Nathalie',
  'DAH-SWN-016',
  'Very pale pink.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-5 inches',
  '3.5 feet',
  '/catalog-seed/sweet-natalie.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '416b8431-7c03-47bb-8506-6de1daac933b',
  'tempest',
  'Tempest',
  'DAH-NEW-132',
  'Warm coral-raspberry dusted with lavender.',
  800,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'e179b26b-2c9c-49cd-b352-fd8ce0931e23',
  'terra-cotta',
  'Terra Cotta',
  'DAH-NEW-133',
  'Warm amber/butterscotch.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '2e2de867-4f2f-492b-a8e9-b95326f8cabc',
  'tiny-treasure',
  'Tiny Treasure',
  'DAH-NEW-134',
  'Ivory/White pompon.',
  1000,
  NULL,
  'sold-out',
  'pompon',
  '["white"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/placeholder-variety.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '850a55b3-b356-4923-92c4-14f013375079',
  'valley-rust-bucket',
  'Valley Rust Bucket',
  'DAH-VRB-052',
  'Bright orange, copper, and rust.',
  1000,
  NULL,
  'sold-out',
  'decorative',
  '["orange","bronze"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/valley-rust-bucket.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  '65a67498-40d5-449c-9cb9-725df3177b90',
  'valley-tawney',
  'Valley Tawney',
  'DAH-NEW-135',
  'Peachy orange, honey yellow, and rose blend.',
  1500,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/valley-tawney.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'd6984d56-492d-4a87-bd64-105a5f84465f',
  'venus',
  'Venus',
  'DAH-VEN-023',
  'Soft peachy-orange (Orchette form).',
  1800,
  NULL,
  'sold-out',
  'decorative',
  '["peach","salmon"]',
  '5-6 inches',
  '4-5 feet',
  '/catalog-seed/venus.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'b14c83cf-a616-4667-8a09-f4ebedba7fa2',
  'wd-brittany',
  'WD Brittany',
  'DAH-WDB-053',
  'Coral pink with gold blush.',
  1400,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/wd-brittany.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'a5a83ed6-ed87-4436-9102-738acb19ac5c',
  'wine-eyed-jill',
  'Wine Eyed Jill',
  'DAH-WEJ-024',
  'Cream, peach, and pink blend with dark eye.',
  800,
  NULL,
  'sold-out',
  'ball',
  '["peach","salmon"]',
  '4-5 inches',
  '3-4 feet',
  '/catalog-seed/win-eyed-jill.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'c7850aa4-6c7f-4650-8d53-46a8fc9f86fa',
  'yelno-harmony',
  'Yelno Harmony',
  'DAH-YEH-025',
  'Warm apricot, peach, and buttery yellow.',
  1400,
  NULL,
  'sold-out',
  'waterlily',
  '["peach","salmon"]',
  '4-5 inches',
  '4 feet',
  '/catalog-seed/yelno-harmony.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

INSERT INTO varieties (
  id,
  slug,
  name,
  sku,
  description,
  price_cents,
  sale_price_cents,
  stock,
  category,
  color_json,
  bloom_size,
  height,
  image_url,
  image_key,
  hidden,
  created_at,
  updated_at
) VALUES (
  'dd6071e9-5fc0-4212-b243-1de22e089c4f',
  'yvonne',
  'Yvonne',
  'DAH-YVN-054',
  'Soft pink/white blend (Waterlily form).',
  1200,
  NULL,
  'sold-out',
  'decorative',
  '["pink","blush"]',
  '4-6 inches',
  '3-4 feet',
  '/catalog-seed/yvonne.jpg',
  NULL,
  0,
  '2026-03-21T03:26:19.153Z',
  '2026-03-21T03:26:19.153Z'
)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  sku = excluded.sku,
  description = excluded.description,
  price_cents = excluded.price_cents,
  sale_price_cents = excluded.sale_price_cents,
  stock = excluded.stock,
  category = excluded.category,
  color_json = excluded.color_json,
  bloom_size = excluded.bloom_size,
  height = excluded.height,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  hidden = excluded.hidden,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;
